import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar';
import Hero from '@/components/Hero';
import About from '@/components/About';
import Head from 'next/head'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
    <Head>
      <title>Phyo Pyae Sone - Portfolio </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <header>
      <Navbar /> 
    </header>

    <main>
      <Hero />
      <About />
    </main>
  </div>
  );
}
